---
#include /includes/aws-sandbox-meta.yaml

# -------------------------------------------------------------------
# --- Catalog Item: DevSecOps Validated Framework - Parallel
# -------------------------------------------------------------------

# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
env_type: ocp4-cluster
software_to_deploy: openshift4
project_tag: "{{ env_type }}-{{ guid }}"

# -------------------------------------------------------------------
# Platform
# -------------------------------------------------------------------
platform: rhpds

# -------------------------------------------------------------------
# Cloud Provider
# -------------------------------------------------------------------
cloud_provider: ec2
bastion_instance_type: t3.medium
bastion_instance_image: RHEL84GOLD-latest

region: us-east-2
cloud_tags:
  env_type: "{{ env_type }}"
  platform: "{{ platform | d('unknown') }}"
aws_region: us-east-2
user_base: student

# -------------------------------------------------------------------
# Common Password
# -------------------------------------------------------------------
common_password: "{{ (guid[:5] | hash('md5') | int(base=16) | b64encode)[:8] }}"

# -------------------------------------------------------------------
# Student User on Bastion
# -------------------------------------------------------------------
install_student_user: true
# --- student_name not set -> Requestor User ID is used as student_name
student_name: dev-admin
# --- student_password not set -> generate random password
student_password: "{{ common_password }}"
# --- Student is allowed to sudo and switch to root
student_sudo: true

# -------------------------------------------------------------------
# Other Variables
# -------------------------------------------------------------------
install_ftl: false

# -------------------------------------------------------------------
# Custom collections for this environment
# -------------------------------------------------------------------
requirements_content:
  collections:
  - name: kubernetes.core
    version: 2.3.1
  - name: openstack.cloud
    version: 1.7.2
  - name: amazon.aws
    version: 2.2.0
  - name: community.general
    version: 4.6.1
  - name: ansible.posix
    version: 1.3.0
  - name: awx.awx
    version: 21.1.0
  - name: ansible.utils
    version: 2.7.0

# -------------------------------------------------------------------
# Workloads
# -------------------------------------------------------------------
infra_workloads:
- ocp4_workload_le_certificates            # all segments
- ocp4_workload_authentication             # all segments
- ocp4_workload_gitea_operator
- ocp4_workload_pipelines
- ocp4_workload_openshift_gitops
- ocp4_workload_codeserver
- ocp4_workload_gitops_aap

# -------------------------------------------------------------------
# Workload: ocp4_workload_authentication
# -------------------------------------------------------------------
ocp4_workload_authentication_idm_type: htpasswd
ocp4_workload_authentication_htpasswd_user_base: "{{ user_base }}"
ocp4_workload_authentication_htpasswd_user_count: "{{ num_users }}"
ocp4_workload_authentication_htpasswd_user_password: "{{ common_password }}"
ocp4_workload_authentication_admin_user: admin
ocp4_workload_authentication_htpasswd_admin_password: "{{ common_password }}"
ocp4_workload_authentication_remove_kubeadmin: false

# -------------------------------------------------------------------
# Workload: ocp4_workload_gitea_operator
# -------------------------------------------------------------------
ocp4_workload_gitea_operator_project: gitea
ocp4_workload_gitea_operator_catalog_image_tag: v1.3.0

ocp4_workload_gitea_operator_deploy_gitea_instance: true
ocp4_workload_gitea_operator_gitea_image: quay.io/gpte-devops-automation/gitea
ocp4_workload_gitea_operator_gitea_image_tag: "1.16.8"
ocp4_workload_gitea_operator_name: gitea
ocp4_workload_gitea_operator_gitea_hostname: gitea
ocp4_workload_gitea_operator_gitea_volume_size: 2Gi
ocp4_workload_gitea_operator_postgresql_volume_size: 2Gi
ocp4_workload_gitea_operator_ssl_route: true

ocp4_workload_gitea_operator_disable_registration: false
ocp4_workload_gitea_operator_enable_captcha: false
ocp4_workload_gitea_operator_allow_create_organization: true
ocp4_workload_gitea_operator_register_email_confirm: false
ocp4_workload_gitea_operator_enable_notify_email: false
ocp4_workload_gitea_operator_mailer_enabled: false

ocp4_workload_gitea_operator_create_admin: true
ocp4_workload_gitea_operator_admin_user: dev-admin
ocp4_workload_gitea_operator_admin_email: dev-admin@opentlc.com
ocp4_workload_gitea_operator_admin_password: "{{ common_password }}"

ocp4_workload_gitea_operator_create_users: true
ocp4_workload_gitea_operator_user_number: "{{ num_users }}"
ocp4_workload_gitea_operator_generate_user_format: "{{ user_base }}%d"
ocp4_workload_gitea_operator_user_password: "{{ common_password }}"
ocp4_workload_gitea_operator_migrate_repositories: true
ocp4_workload_gitea_operator_repositories_list:
- repo: https://github.com/redhat-gpte-devopsautomation/workshop_project.git
  name: workshop_project
  private: false

# ---------------------------------------------------------
# Workload: OpenShift Pipelines
# ---------------------------------------------------------
ocp4_workload_pipelines_channel: pipelines-1.7
ocp4_workload_pipelines_tkn_version: 0.23.1
ocp4_workload_pipelines_csv_nameprefix: openshift-pipelines-operator-rh
ocp4_workload_pipelines_use_catalog_snapshot: true
ocp4_workload_pipelines_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_pipelines_catalog_snapshot_image_tag: v4.10_2022_06_06

# -------------------------------------------------------------------
# Workload: ocp4_workload_openshift_gitops
# -------------------------------------------------------------------
ocp4_workload_openshift_gitops_channel: stable
ocp4_workload_openshift_gitops_pipelines_csv_prefix: openshift-pipelines-operator-rh
ocp4_workload_openshift_gitops_use_catalog_snapshot: true
ocp4_workload_openshift_gitops_catalogsource_name: redhat-operators-snapshot-gitops
ocp4_workload_openshift_gitops_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_openshift_gitops_catalog_snapshot_image_tag: v4.10_2022_06_06

# -------------------------------------------------------------------
# Workload: ocp4_workload_codeserver
# -------------------------------------------------------------------
ocp4_workload_openshift_gitops_setup_cluster_admin: true
ocp4_workload_codeserver_name: codeserver
ocp4_workload_codeserver_workspace_name: ide
ocp4_workload_codeserver_password: "{{ common_password }}"
ocp4_workload_codeserver_pvc_size: 3Gi
ocp4_workload_codeserver_gitea_name: gitea
ocp4_workload_codeserver_gitea_namespace: gitea
ocp4_workload_codeserver_extensions:
- filename: auchenberg.vscode-browser-preview-0.7.2.vsix
  url: https://gpte-public.s3.amazonaws.com/vscode-plugins/auchenberg.vscode-browser-preview-0.7.2.vsix

ocp4_workload_codeserver_multi_user_install: true
ocp4_workload_codeserver_multi_user_num_users: "{{ num_users }}"
ocp4_workload_codeserver_multi_user_username_base: "{{ user_base }}"
ocp4_workload_codeserver_multi_user_namespace_base: workshop
ocp4_workload_codeserver_repos_user: "{{ user_base }}1"
ocp4_workload_codeserver_repos_password: "{{ common_password }}"
# ocp4_workload_codeserver_repos:
# - name: workshop_project
#   branch: main

# -------------------------------------------------------------------
# Workload: ocp4_workload_gitops_aap
# -------------------------------------------------------------------
ocp4_workload_gitops_aap_install_controller: true
ocp4_workload_gitops_aap_install_hub: false
ocp4_workload_gitops_aap_enable_multiuser_controller: true
ocp4_workload_gitops_aap_multiuser_num_users: "{{ num_users }}"
ocp4_workload_gitops_aap_multiuser_username_base: "{{ user_base }}"
ocp4_workload_gitops_aap_multiuser_namespace_base: workshop


# --- Student Workloads (YAML List)
student_workloads: []

# -------------------------------------------------------------------
# AgnosticV meta variables
# -------------------------------------------------------------------

agnosticv_meta:
  sandboxed: false
  idle_after_deploy: 9999
  idle_after_start: 9999
  deploy_with: babylon

# -------------------------------------------------------------------
# Babylon meta variables
# -------------------------------------------------------------------
__meta__:
  anarchy:
    namespace: babylon-anarchy-sandboxes-gpte
  deployer:
    virtualenv: ansible2.9-python3.6-2021-11-30
  catalog:
    namespace: babylon-catalog-{{ stage | default('?') }}
    display_name: Base Infra AAP2 on OCP4
    category: Demos
    keywords:
    - aap2
    - baseinfra
    - dev
    parameters:
    - name: num_users
      description: >-
        Number of users to provision within the cluster.
      formLabel: OpenShift User Count
      openAPIV3Schema:
        type: integer
        default: 2
        minimum: 1
        maximum: 50
    labels:
      Product: Red_Hat_OpenShift_Container_Platform
      Product_Family: Red_Hat_Cloud
      Provider: RHDP
  
